"use client";
import * as React from "react";
import { BookOpen, ChevronDown, ChevronRight, FileText, Folder, Hash, Link2, Network, Plus, Search, Settings2, Star } from "lucide-react";
import { GlassPanel } from "@/components/ui/glass-panel";
import { SearchField } from "@/components/ui/search-field";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { KnowledgeGraph, type ResearchGraphNode } from "@/components/product/knowledge-graph";
import type { Edge } from "@xyflow/react";

const nodes: ResearchGraphNode[]=[
 {id:"a",type:"research",position:{x:0,y:100},data:{kind:"concept",title:"Biomass Co-firing",subtitle:"hub note",strength:100}},
 {id:"b",type:"research",position:{x:280,y:0},data:{kind:"paper",title:"CFB hydrodynamics",subtitle:"paper note",strength:84}},
 {id:"c",type:"research",position:{x:280,y:190},data:{kind:"concept",title:"Alkali / slagging",subtitle:"concept note",strength:74}},
 {id:"d",type:"research",position:{x:560,y:40},data:{kind:"method",title:"Eulerian CFD",subtitle:"method",strength:77}},
 {id:"e",type:"research",position:{x:560,y:230},data:{kind:"equation",title:"Reaction kinetics",subtitle:"Arrhenius",strength:82}}
];
const edges:Edge[]=[{id:"1",source:"a",target:"b"},{id:"2",source:"a",target:"c"},{id:"3",source:"b",target:"d"},{id:"4",source:"c",target:"e"}];

export function KnowledgeWorkspace(){ const [q,setQ]=React.useState(""); const [tab,setTab]=React.useState<"note"|"graph">("note"); return <div className="grid min-h-[760px] gap-3 lg:grid-cols-[240px_minmax(0,1fr)_270px]">
 <GlassPanel className="overflow-hidden p-2"><div className="px-2 py-2"><div className="flex items-center justify-between"><div><div className="text-sm font-semibold">Engineering Vault</div><div className="text-[10px] text-[var(--muted)]">1,248 notes · local workspace</div></div><Button size="icon" variant="ghost" className="size-8"><Plus className="size-4"/></Button></div><SearchField value={q} onChange={e=>setQ(e.target.value)} onClear={()=>setQ("")} placeholder="Search vault…" className="mt-3"/></div><div className="mt-1 space-y-1 px-1 text-xs"><div className="flex items-center gap-2 rounded-lg bg-black/[.05] px-2 py-2 font-medium dark:bg-white/[.07]"><Folder className="size-3.5"/>01 Projects<ChevronDown className="ml-auto size-3.5"/></div>{["CFB Co-firing","EFB Torrefaction","PT.SATU Pre-FEED"].map(x=><div key={x} className="ml-4 flex items-center gap-2 rounded-lg px-2 py-1.5 text-[var(--muted)] hover:bg-black/[.04] dark:hover:bg-white/[.06]"><FileText className="size-3.5"/>{x}</div>)}<div className="mt-2 flex items-center gap-2 rounded-lg px-2 py-2 text-[var(--muted)]"><Folder className="size-3.5"/>02 Literature<ChevronRight className="ml-auto size-3.5"/></div><div className="flex items-center gap-2 rounded-lg px-2 py-2 text-[var(--muted)]"><Star className="size-3.5"/>Pinned</div></div></GlassPanel>
 <GlassPanel className="overflow-hidden"><div className="flex h-12 items-center justify-between border-b border-[var(--line)] px-4"><div className="flex items-center gap-2"><button onClick={()=>setTab("note")} className={`rounded-lg px-2.5 py-1.5 text-xs ${tab==="note"?"bg-[var(--foreground)] text-[var(--background)]":"text-[var(--muted)]"}`}>Note</button><button onClick={()=>setTab("graph")} className={`rounded-lg px-2.5 py-1.5 text-xs ${tab==="graph"?"bg-[var(--foreground)] text-[var(--background)]":"text-[var(--muted)]"}`}>Graph</button></div><div className="flex items-center gap-2 text-[var(--muted)]"><Link2 className="size-4"/><Network className="size-4"/><Settings2 className="size-4"/></div></div>{tab==="graph"?<div className="p-3"><KnowledgeGraph nodes={nodes} edges={edges} className="h-[680px]"/></div>:<article className="mx-auto max-w-3xl px-8 py-12 md:px-12"><div className="flex items-center gap-2 text-[10px] text-[var(--muted)]"><span>Projects</span><ChevronRight className="size-3"/><span>CFB Co-firing</span></div><h1 className="mt-5 text-4xl font-semibold tracking-[-.045em]">Biomass co-firing — research map</h1><div className="mt-4 flex flex-wrap gap-2"><Badge tone="blue">CFB</Badge><Badge tone="green">biomass</Badge><Badge tone="violet">PoC</Badge></div><p className="mt-8 text-[15px] leading-7 text-[var(--muted)]">This note is the synthesis layer between literature, simulation assumptions, experimental data and operational constraints. It is designed to remain readable during long research sessions rather than to look like a dashboard.</p><h2 className="mt-10 text-xl font-semibold tracking-[-.03em]">Research questions</h2><ul className="mt-4 space-y-3 text-sm leading-6"><li className="rounded-xl border border-[var(--line)] bg-black/[.02] p-3 dark:bg-white/[.03]">How does torrefaction alter devolatilization and ignition behavior?</li><li className="rounded-xl border border-[var(--line)] bg-black/[.02] p-3 dark:bg-white/[.03]">Which ash chemistry variables dominate agglomeration risk at higher substitution ratios?</li><li className="rounded-xl border border-[var(--line)] bg-black/[.02] p-3 dark:bg-white/[.03]">Which CFD parameters should be validated against pilot measurements?</li></ul><div className="mt-9 rounded-2xl border-l-4 border-blue-500 bg-blue-500/[.06] p-4 text-sm leading-6"><strong>Linked insight.</strong> Hemicellulose decomposition improves grindability, but the downstream combustion model still needs particle-size and volatile-yield sensitivity.</div></article>}</GlassPanel>
 <GlassPanel className="overflow-hidden p-4"><div className="text-[10px] font-semibold uppercase tracking-[.14em] text-[var(--muted)]">Backlinks</div><div className="mt-3 space-y-2">{["CFB hydrodynamics review","EFB fuel properties","PoC validation plan"].map((x,i)=><div key={x} className="rounded-xl border border-[var(--line)] bg-black/[.025] p-3 dark:bg-white/[.035]"><div className="flex items-center gap-2 text-xs font-semibold"><FileText className="size-3.5"/>{x}</div><p className="mt-1.5 text-[10px] leading-4 text-[var(--muted)]">Mentions this note in {i+1} linked context{i?"s":""}.</p></div>)}</div><div className="mt-6 text-[10px] font-semibold uppercase tracking-[.14em] text-[var(--muted)]">Properties</div><div className="mt-3 space-y-2 text-xs">{[["status","active"],["owner","research"],["updated","today"]].map(([a,b])=><div key={a} className="flex justify-between rounded-lg py-1.5"><span className="text-[var(--muted)]">{a}</span><span className="font-medium">{b}</span></div>)}</div></GlassPanel>
 </div>; }
