"use client";
import * as React from "react";
import { Background, BackgroundVariant, Controls, Handle, MiniMap, Position, ReactFlow, type Edge, type Node, type NodeProps } from "@xyflow/react";
import { BookOpen, FlaskConical, Lightbulb, Sigma } from "lucide-react";
import { cn } from "@/lib/utils";

export type ResearchNodeKind = "paper" | "concept" | "method" | "equation";
export type ResearchNodeData = { title: string; subtitle?: string; kind: ResearchNodeKind; strength?: number };
export type ResearchGraphNode = Node<ResearchNodeData, "research">;
const kindMeta = { paper:{ icon:BookOpen, label:"Paper" }, concept:{ icon:Lightbulb, label:"Concept" }, method:{ icon:FlaskConical, label:"Method" }, equation:{ icon:Sigma, label:"Equation" } } as const;
function ResearchNodeCard({ data, selected }: NodeProps<ResearchGraphNode>) { const meta=kindMeta[data.kind]; const Icon=meta.icon; return <div className={cn("min-w-44 rounded-[16px] border bg-[var(--surface-strong)] p-3 shadow-lg backdrop-blur-xl transition", selected ? "border-[var(--accent)] shadow-[0_0_0_4px_rgba(10,132,255,.10)]" : "border-[var(--line)]")}><Handle type="target" position={Position.Left} className="!size-2 !border-0 !bg-[var(--muted)]"/><div className="flex items-start gap-2.5"><div className="grid size-8 shrink-0 place-items-center rounded-xl bg-black/[.05] text-[var(--muted)] dark:bg-white/[.07]"><Icon className="size-4"/></div><div className="min-w-0"><div className="text-[9px] font-semibold uppercase tracking-[.12em] text-[var(--muted)]">{meta.label}</div><div className="mt-0.5 max-w-48 truncate text-xs font-semibold">{data.title}</div>{data.subtitle ? <div className="mt-1 max-w-48 truncate text-[10px] text-[var(--muted)]">{data.subtitle}</div>:null}</div></div>{data.strength!==undefined ? <div className="mt-2 h-1 overflow-hidden rounded-full bg-black/[.06] dark:bg-white/[.08]"><div className="h-full rounded-full bg-[var(--foreground)]" style={{width:`${Math.max(0,Math.min(100,data.strength))}%`}}/></div>:null}<Handle type="source" position={Position.Right} className="!size-2 !border-0 !bg-[var(--muted)]"/></div>; }
const nodeTypes = { research: ResearchNodeCard };
export function KnowledgeGraph({ nodes, edges, onNodeSelect, className }: { nodes: ResearchGraphNode[]; edges: Edge[]; onNodeSelect?: (node:ResearchGraphNode)=>void; className?: string }) { return <div className={cn("h-[540px] overflow-hidden rounded-[20px] border border-[var(--line)] bg-[var(--surface)]", className)}><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} fitView fitViewOptions={{padding:.25}} minZoom={.25} maxZoom={2} onNodeClick={(_,node)=>onNodeSelect?.(node as ResearchGraphNode)} proOptions={{hideAttribution:true}}><Background variant={BackgroundVariant.Dots} gap={22} size={1} color="rgba(127,127,127,.23)"/><MiniMap zoomable pannable className="!rounded-xl !border !border-[var(--line)] !bg-[var(--surface-strong)]" maskColor="rgba(127,127,127,.08)"/><Controls showInteractive={false} className="!overflow-hidden !rounded-xl !border !border-[var(--line)] !bg-[var(--surface-strong)] !shadow-lg [&_button]:!border-[var(--line)] [&_button]:!bg-transparent [&_button]:!fill-current"/></ReactFlow></div>; }
