"use client";
import * as React from "react";
import { Activity, AlertTriangle, CheckCircle2, Droplets, Fan, Flame, Gauge, MoveRight, Power, ThermometerSun, Waves } from "lucide-react";
import { GlassPanel } from "@/components/ui/glass-panel";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

function Sparkline({values}:{values:number[]}){const max=Math.max(...values),min=Math.min(...values);const pts=values.map((v,i)=>`${(i/(values.length-1))*100},${36-((v-min)/(max-min||1))*30}`).join(" ");return <svg viewBox="0 0 100 40" className="h-12 w-full overflow-visible"><polyline points={pts} fill="none" stroke="currentColor" strokeWidth="2" vectorEffect="non-scaling-stroke"/><line x1="0" y1="36" x2="100" y2="36" stroke="currentColor" opacity=".12"/></svg>}
function UnitCard({label,value,unit,icon:Icon,state="normal",values}:{label:string;value:string;unit:string;icon:React.ElementType;state?:"normal"|"warn"|"alarm";values:number[]}){return <GlassPanel className={cn("p-4",state==="warn"&&"border-amber-500/35",state==="alarm"&&"border-red-500/40")}><div className="flex items-center justify-between"><span className="text-[11px] font-medium text-[var(--muted)]">{label}</span><Icon className={cn("size-4 text-[var(--muted)]",state==="warn"&&"text-amber-500",state==="alarm"&&"text-red-500")}/></div><div className="mt-2 flex items-baseline gap-1.5"><span className="text-2xl font-semibold tabular-nums tracking-[-.04em]">{value}</span><span className="text-[10px] font-medium text-[var(--muted)]">{unit}</span></div><div className={cn("mt-1 text-[var(--foreground)]",state==="warn"&&"text-amber-500",state==="alarm"&&"text-red-500")}><Sparkline values={values}/></div></GlassPanel>}

export function EngineeringConsole(){const [running,setRunning]=React.useState(true);return <div className="space-y-3"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><div className="flex items-center gap-2"><h2 className="text-xl font-semibold tracking-[-.035em]">Pilot Process Console</h2><Badge tone={running?"green":"neutral"}>{running?"RUNNING":"IDLE"}</Badge></div><p className="mt-1 text-xs text-[var(--muted)]">Wash → dewater → dry → pellet · operator-focused engineering layout</p></div><div className="flex gap-2"><Button variant="secondary"><Activity className="size-4"/>Historian</Button><Button variant={running?"danger":"accent"} onClick={()=>setRunning(v=>!v)}><Power className="size-4"/>{running?"Stop run":"Start run"}</Button></div></div>
<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><UnitCard label="Steam header" value="2.48" unit="bar(g)" icon={Waves} values={[2.4,2.44,2.43,2.49,2.48,2.51,2.48]}/><UnitCard label="Steam flow" value="361" unit="kg/h" icon={Gauge} values={[342,350,348,359,364,360,361]}/><UnitCard label="Dryer outlet" value="112.6" unit="°C" icon={ThermometerSun} state="warn" values={[104,106,108,110,113,114,112.6]}/><UnitCard label="Product moisture" value="9.4" unit="wt%" icon={Droplets} values={[11.2,10.8,10.3,10,9.7,9.5,9.4]}/></div>
<GlassPanel className="overflow-hidden"><div className="flex items-center justify-between border-b border-[var(--line)] px-4 py-3"><div><div className="text-sm font-semibold">Process line</div><div className="text-[10px] text-[var(--muted)]">Equipment state and material direction</div></div><Badge tone="green">Stable</Badge></div><div className="grid gap-3 p-4 lg:grid-cols-[1fr_auto_1fr_auto_1fr_auto_1fr] lg:items-center">{[
 {n:"W-101",name:"POME Washer",icon:Droplets,status:"1.225 t/h raw"},{n:"D-201",name:"Decanter",icon:Waves,status:"1.05 t/h cake"},{n:"DR-301",name:"Indirect Dryer",icon:Fan,status:"0.655 t/h dry"},{n:"P-401",name:"Pellet Mill",icon:Flame,status:"0.625 t/h product"}
].map((x,i)=><React.Fragment key={x.n}><div className="rounded-2xl border border-[var(--line)] bg-black/[.025] p-4 dark:bg-white/[.035]"><div className="flex items-start justify-between"><div className="grid size-9 place-items-center rounded-xl bg-[var(--foreground)] text-[var(--background)]"><x.icon className="size-4"/></div><span className="text-[9px] font-semibold text-emerald-500">RUN</span></div><div className="mt-4 text-[10px] text-[var(--muted)]">{x.n}</div><div className="mt-0.5 text-sm font-semibold">{x.name}</div><div className="mt-2 text-xs tabular-nums text-[var(--muted)]">{x.status}</div></div>{i<3?<MoveRight className="mx-auto hidden size-5 text-[var(--muted)]/50 lg:block"/>:null}</React.Fragment>)}</div></GlassPanel>
<div className="grid gap-3 lg:grid-cols-[1.3fr_.7fr]"><GlassPanel className="p-4"><div className="flex items-center justify-between"><div><div className="text-sm font-semibold">Shift timeline</div><div className="text-[10px] text-[var(--muted)]">Events aligned to operator decisions</div></div><span className="text-[10px] text-[var(--muted)]">08:00 — 16:00</span></div><div className="mt-5 space-y-4">{[["08:12","Feed started","normal"],["10:36","Dryer outlet approached high limit","warn"],["11:05","Steam valve trimmed −4%","normal"],["13:48","Moisture back below target","normal"]].map(([t,e,s])=><div key={t} className="grid grid-cols-[52px_12px_1fr] items-center gap-3 text-xs"><span className="font-mono text-[var(--muted)]">{t}</span><span className={cn("size-2.5 rounded-full",s==="warn"?"bg-amber-500":"bg-emerald-500")}/><span>{e}</span></div>)}</div></GlassPanel><GlassPanel className="overflow-hidden"><div className="border-b border-[var(--line)] px-4 py-3"><div className="flex items-center gap-2 text-sm font-semibold"><AlertTriangle className="size-4 text-amber-500"/>Alarm queue</div></div><div className="divide-y divide-[var(--line)]">{[["High dryer outlet","HH 125 °C","warn"],["Decanter vibration","4.2 mm/s","normal"],["POME tank level","62 %","normal"]].map(([a,b,s])=><div key={a} className="flex items-center justify-between p-4"><div><div className="text-xs font-semibold">{a}</div><div className="mt-1 text-[10px] text-[var(--muted)]">{b}</div></div>{s==="warn"?<AlertTriangle className="size-4 text-amber-500"/>:<CheckCircle2 className="size-4 text-emerald-500"/>}</div>)}</div></GlassPanel></div></div>}
