"use client";
import Link from "next/link";
import { ArrowLeft, ChevronLeft, ChevronRight, Columns2, PanelLeft, Minus, Plus, Moon, Sun, Command, Download, Search } from "lucide-react";
import { IconButton } from "@/components/ui/icon-button";
import { Button } from "@/components/ui/button";
import { useReaderStore } from "@/lib/paperflow/state/reader-store";
import { usePaperflow } from "../shell/paperflow-context";
export function ReaderToolbar({ title, pages, page, effectiveZoom, onPage, onSearch, onDownload }: { title: string; pages: number; page: number; effectiveZoom: number; onPage: (page: number) => void; onSearch: () => void; onDownload: () => void }) {
  const { dark, toggleTheme, openCommand } = usePaperflow();
  const zoom = effectiveZoom, fit = useReaderStore(s => s.fitMode), inspector = useReaderStore(s => s.inspectorOpen), rail = useReaderStore(s => s.pageRailOpen), set = useReaderStore(s => s.set);
  return <><header className="pf-reader-top"><div className="pf-reader-title"><IconButton asChild label="Open Library" variant="ghost"><Link href="/library"><ArrowLeft size={18}/></Link></IconButton><div><span className="pf-kicker">PAPERFLOW / READER</span><h1 title={title}>{title}</h1></div></div><div className="pf-toolbar-group"><span className="pf-local-badge">● Local PDF</span><IconButton label="Download original PDF" variant="ghost" onClick={onDownload}><Download size={17}/></IconButton><IconButton label="Toggle theme" variant="ghost" onClick={toggleTheme}>{dark ? <Sun size={17}/> : <Moon size={17}/>}</IconButton><IconButton label="Open command menu" variant="ghost" onClick={openCommand}><Command size={17}/></IconButton></div></header>
    <div className="pf-reader-tools"><div className="pf-toolbar-group"><IconButton label="Toggle page rail" aria-expanded={rail} variant="ghost" onClick={() => set({ pageRailOpen: !rail })}><PanelLeft size={16}/></IconButton><span className="pf-divider"/><IconButton label="Previous page" variant="ghost" disabled={page <= 1} onClick={() => onPage(page - 1)}><ChevronLeft size={17}/></IconButton><label className="pf-page-input"><input aria-label="Page number" type="number" min={1} max={pages} value={page} onChange={e => { const value = Number(e.target.value); if (value >= 1 && value <= pages) onPage(value); }}/><span>/ {pages}</span></label><IconButton label="Next page" variant="ghost" disabled={page >= pages} onClick={() => onPage(page + 1)}><ChevronRight size={17}/></IconButton></div>
      <div className="pf-toolbar-group pf-zoom-controls"><IconButton label="Zoom out" variant="ghost" disabled={zoom <= 25} onClick={() => set({ zoom: Math.max(25, zoom - 10), fitMode: "custom", activeSelection: null })}><Minus size={16}/></IconButton><span className="pf-zoom-label">{fit === "custom" ? `${zoom}%` : fit === "width" ? "Fit width" : "Fit page"}</span><IconButton label="Zoom in" variant="ghost" disabled={zoom >= 250} onClick={() => set({ zoom: Math.min(250, zoom + 10), fitMode: "custom", activeSelection: null })}><Plus size={16}/></IconButton><Button size="sm" variant="ghost" onClick={() => set({ fitMode: fit === "width" ? "page" : "width", activeSelection: null })}>맞춤</Button></div>
      <div className="pf-toolbar-group"><span className="pf-original-label">Original</span><IconButton label="Search paper" variant="ghost" onClick={onSearch}><Search size={16}/></IconButton><IconButton label="Toggle inspector" aria-expanded={inspector} variant="ghost" onClick={() => set({ inspectorOpen: !inspector })}><Columns2 size={16}/></IconButton></div>
    </div></>;
}
