"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, ChevronLeft, ChevronRight, Columns2, PanelLeft, Minus, Plus, Moon, Sun, Command, Download, Search, Languages } from "lucide-react";
import { IconButton } from "@/components/ui/icon-button";
import { Button } from "@/components/ui/button";
import { useReaderStore } from "@/lib/paperflow/state/reader-store";
import { usePaperflow } from "../shell/paperflow-context";
export function ReaderToolbar({ title, pages, page, effectiveZoom, onPage, onSearch, onDownload, onBatchTranslate, batchRunning, canTranslate }: { title: string; pages: number; page: number; effectiveZoom: number; onPage: (page: number) => void; onSearch: () => void; onDownload: () => void; onBatchTranslate: () => void; batchRunning: boolean; canTranslate: boolean }) {
  const { dark, toggleTheme, openCommand } = usePaperflow();
  const zoom = effectiveZoom, fit = useReaderStore(s => s.fitMode), inspector = useReaderStore(s => s.inspectorOpen), rail = useReaderStore(s => s.pageRailOpen), set = useReaderStore(s => s.set);
  const [draftZoom, setDraftZoom] = useState(zoom);
  useEffect(() => setDraftZoom(zoom), [zoom]);
  const commitZoom = (value: number) => set({ zoom: value, fitMode: "custom", activeSelection: null });
  return <><header className="pf-reader-top"><div className="pf-reader-title"><IconButton asChild label="Open Library" variant="ghost"><Link href="/library"><ArrowLeft size={18}/></Link></IconButton><div><span className="pf-kicker">PAPERFLOW / READER</span><h1 title={title}>{title}</h1></div></div><div className="pf-toolbar-group"><span className="pf-local-badge">● Local PDF</span><IconButton label="Download original PDF" variant="ghost" onClick={onDownload}><Download size={17}/></IconButton><IconButton label="Toggle theme" variant="ghost" onClick={toggleTheme}>{dark ? <Sun size={17}/> : <Moon size={17}/>}</IconButton><IconButton label="Open command menu" variant="ghost" onClick={openCommand}><Command size={17}/></IconButton></div></header>
    <div className="pf-reader-tools"><div className="pf-toolbar-group"><IconButton label="Toggle page rail" aria-expanded={rail} variant="ghost" onClick={() => set({ pageRailOpen: !rail })}><PanelLeft size={16}/></IconButton><span className="pf-divider"/><IconButton label="Previous page" variant="ghost" disabled={page <= 1} onClick={() => onPage(page - 1)}><ChevronLeft size={17}/></IconButton><label className="pf-page-input"><input aria-label="Page number" type="number" min={1} max={pages} value={page} onChange={e => { const value = Number(e.target.value); if (value >= 1 && value <= pages) onPage(value); }}/><span>/ {pages}</span></label><IconButton label="Next page" variant="ghost" disabled={page >= pages} onClick={() => onPage(page + 1)}><ChevronRight size={17}/></IconButton></div>
      <div className="pf-toolbar-group pf-zoom-controls"><IconButton label="Zoom out" variant="ghost" disabled={zoom <= 25} onClick={() => commitZoom(Math.max(25, zoom - 10))}><Minus size={16}/></IconButton><label className="pf-zoom-dial"><input aria-label="확대 비율" aria-valuetext={`${draftZoom}%`} type="range" min={25} max={250} step={5} value={draftZoom} onChange={event => setDraftZoom(Number(event.target.value))} onPointerUp={event => commitZoom(Number(event.currentTarget.value))} onPointerCancel={() => setDraftZoom(zoom)} onKeyUp={event => commitZoom(Number(event.currentTarget.value))} onBlur={() => { if (draftZoom !== zoom) commitZoom(draftZoom); }}/><span className="pf-zoom-label">{draftZoom !== zoom || fit === "custom" ? `${draftZoom}%` : fit === "width" ? "너비 맞춤" : "페이지 맞춤"}</span></label><IconButton label="Zoom in" variant="ghost" disabled={zoom >= 250} onClick={() => commitZoom(Math.min(250, zoom + 10))}><Plus size={16}/></IconButton><Button size="sm" variant="ghost" onClick={() => set({ fitMode: fit === "width" ? "page" : "width", activeSelection: null })}>맞춤</Button></div>
      <div className="pf-toolbar-group"><span className="pf-original-label">Original</span><Button className="pf-batch-button" size="sm" variant="ghost" disabled={!canTranslate || batchRunning} onClick={onBatchTranslate}><Languages size={15}/>{batchRunning ? "번역 중…" : "현재 페이지 일괄 번역"}</Button><IconButton label="Search paper" variant="ghost" onClick={onSearch}><Search size={16}/></IconButton><IconButton label="Toggle inspector" aria-expanded={inspector} variant="ghost" onClick={() => set({ inspectorOpen: !inspector })}><Columns2 size={16}/></IconButton></div>
    </div></>;
}
